name: X to Telegram Bot

on:
  schedule:
    # Run every 30 minutes to process one account at a time
    - cron: '0,30 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  forward-posts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run bot (one account per run)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          ORAICHAIN_TOPIC_ID: ${{ secrets.ORAICHAIN_TOPIC_ID }}
          BABYLON_TOPIC_ID: ${{ secrets.BABYLON_TOPIC_ID }}
        run: python main.py
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add processed_tweets.json account_rotation.txt user_ids.json
          git commit -m "Update bot state files" || echo "No changes to commit"
          git push